### ISSUE TITLE
Unable to Send Transaction - Too Many Parameters

### ISSUE THREAD

**Issue by phillc73** [kvhnuke/MyEtherWalletChromeExtension#1]
Trying to send Eth in a transaction (my first) and receive the following error after clicking Generate Transaction:

"Whoops. There was an error. Too many params, want 1 got 2"

Using Chromium Version 49.0.2623.108 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

**Comment by kingflurkel** [comment]
+1

**Comment by sponnet** [comment]
It the underlying geth node that logs this error. This wallet merely displays it. But the transactions seem to fail.

**Comment by sponnet** [comment]
I just followed the transaction flow in the debug window till the endpoint ( https://rpc.myetherwallet.com/api.php ) and it seems to work now.
Was something changed on the API-endpoint ? Everything up to the POST of the signed transaction seems to work without any problem client side. 
I can't see if anything was changed server-side.

**Comment by tayvano** [comment]
Oh shoot. I forgot to respond here (we also received like 10 emails)

We updated MyEtherWallet.com @ 5am when our geth node went down and in doing so broke the Chrome Extension. We fixed this new issue with the CX yesterday. It was a problem that happens in the relay (I believe). 

Should be resolved.

**Comment by tayvano** [comment]
We've also added the api.php here so it can be tracked in the future. 

https://github.com/kvhnuke/etherwallet/tree/mercury/php_json_relay

**Comment by phillc73** [comment]
Thanks for the update. 

Unfortunately, I'm seeing a "Gas limit too low" message now.

**Comment by tayvano** [comment]
Gosh dang it. Lemme check on it. Can you post the address that you're getting the error from, or (if you don't want to publicly) email me it at myetherwallet@gmail.com

**Comment by phillc73** [comment]
Sorry, I deleted the "Gas Limit too Low" comment just a few seconds ago, as I actually found the messaging in the Help/FAQ. Let me actually help myself by reading those pages, and I'll let you know if it still fails.

Thanks for your patience so far.

**Comment by tayvano** [comment]
Ha! Good to hear. I'm here if you need me, keep me posted.

**Comment by phillc73** [comment]
I think i'm all fixed.

I was, in short, trying to buy DAO tokens, which is sending to a contract. Therefore, needed more gas. I see a green transaction successfully submitted message, so all looks fine.

Thanks for your help. I'll close this issue.
